### ISSUE TITLE
RuntimeException Index invalid or out of range

### ISSUE THREAD

**Issue by Ahmard** [endroid/qr-code#365] opened 2022-01-26 09:54 UTC
Hello there, I was playing around with this lib and keeps getting "RuntimeException Index invalid or out of range" exception.
I am using PHP 8.0 by the way.
Below is the screenshot of the error

![Screenshot from 2022-01-26 10-49-08](https://user-images.githubusercontent.com/44737217/151141402-75d54eda-710b-4478-b8de-87920ab2b329.png)
.

**Comment by Ahmard** [comment] 2022-01-26 09:54
This is is the code throwing the exception

![Screenshot from 2022-01-26 10-50-28](https://user-images.githubusercontent.com/44737217/151141615-d58427f8-3a21-4433-a60c-1125f8747d0a.png)

**Comment by endroid** [comment] 2022-01-26 10:13
https://github.com/endroid/qr-code/issues/362

**Comment by endroid** [comment] 2022-01-26 10:19
Hi @Ahmard thank you. We are waiting for a fix for this. See https://github.com/Bacon/BaconQrCode/issues/92.

**Comment by Ahmard** [comment] 2022-01-26 11:39
Okay sir, thank you.

**Comment by Ahmard** [comment] 2022-01-26 11:39
Can you suggest any alternative matrix please?

**Comment by acelaya** [comment] 2022-01-30 17:56
It doesn't seem that library is ever going to get a fix. The issue is 4 months old, and the library hasn't published a new version in 4 years.

Is there any way to work around it?

**Comment by endroid** [comment] 2022-01-30 22:34
Hi, I have searched but could not find a useful replacement yet and I still have hope the maintainer will find a fix like he always did in the past. The repository has served well for many years and the last commit date of 7 months ago is a reason to look for alternatives, but I will mention the maintainer and hope we can continue to use that library. But of course if anyone finds a replacement in the meantime, please let me know.

**Comment by acelaya** [comment] 2022-01-30 22:38
Thanks for taking the time 🙂

**Comment by endroid** [comment] 2022-01-31 11:15
@Ahmard we are looking into the issue. I added your example to the test suite and it runs correctly in CI. However there are some variables in your script, can you post the values that result in the error? And could you check your composer.lock file to see what version of bacon qr code you are using? That would help us, thank you.

**Comment by Ahmard** [comment] 2022-01-31 11:22
This is where I call it
![Screenshot from 2022-01-31 12-20-48](https://user-images.githubusercontent.com/44737217/151785182-1bcc3a6b-2e89-42aa-8787-075f01c3ae3a.png)

**Comment by endroid** [comment] 2022-01-31 11:30
Thank you, updated the test case to it uses those values. Still no exception however. What exact version of bacon qr code are you using according to your composer.lock file?

**Comment by acelaya** [comment] 2022-01-31 11:33
This looks like a very tricky one. I got this reportedt by a user, on a project where I depend on endroid/qr-code.

I was not able to reproduce it with any combination of options. Later, when I requested more info to the user, he was no longer able to reproduce it either.

@Ahmard is it happening consistently for you?

**Comment by endroid** [comment] 2022-01-31 11:34
@acelaya or @PhoenixBWS maybe any of you can provide a failing test case?

**Comment by acelaya** [comment] 2022-01-31 11:36
As I was saying, I haven't been able to reproduce it myself 😅. I have tried, but no "luck" so far.

**Comment by endroid** [comment] 2022-01-31 11:36
@acelaya thanks for your input. Our messages crossed ;) Ran it in a loop for 100 times now, no errors. Indeed tricky ;)

**Comment by PhoenixBWS** [comment] 2022-01-31 12:26
@endroid Sure. I'll be glad to help, for I desperately want your QRCode library to work with my PHP 8.1.2 system. The OS I'm using is **Ubuntu 20.04 LTS Focal Fossa** running on top of **NGINX Open Sourse 1.18.x** and I usually make all PHP files respond through the **index.php** file like Wordpress. In this case my index.php was doing the equivalent of the following code:

```
<?php

include_once 'vendor/autoload.php';
include_once 'pages/qr.php';

?>
```

The **qr.php** file inside the **pages** echoes the output that one would expect. And it had the codes like so:

```
<?php

use Endroid\QrCode\Color\Color;
use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\ErrorCorrectionLevel\ErrorCorrectionLevelHigh;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\RoundBlockSizeMode\RoundBlockSizeModeMargin;
use Endroid\QrCode\Writer\PngWriter;

// Some more codes to handle input queries in my script and then

        $writer = new PngWriter();
        // Create QR code
        $qrCode = QrCode::create('https://xxxxxxx.xxxx/xxxxxxx')
            -> setEncoding(new Encoding('UTF-8'))
            -> setErrorCorrectionLevel(new ErrorCorrectionLevelHigh())
            -> setSize(1200)
            -> setMargin(40)
            -> setRoundBlockSizeMode(new RoundBlockSizeModeMargin())
            -> setForegroundColor(new Color(0, 0, 0))
            -> setBackgroundColor(new Color(255, 255, 255, 127));

        $result = $writer -> write($qrCode);

// Then I did some imagick stuff with the result

        $im = new Imagick();
        $im -> readImageBlob($result -> getString());

// And so on

?>
```

Strange thing was that whenever I used PHP 8.0 or 8.1, I ended up getting the same error. But the same code is working flawlessly without generating any issue or warning as soon as I switched back to PHP 7.4 for my portal.

I have used your library in some of my other projects as well. And when I shifted those sites to PHP 8.x the same issue started appearing on them too. Therefore I got to downgrade them again. All of those sites are now on PHP 7.4 and they're working fine in it.

Hope this information helps.

**Comment by Ahmard** [comment] 2022-01-31 14:07
I wasn't able to reproduce the error either 😅
I removed the "composer.lock file and vendor dir" then I ran "composer require endroid/qr-code" again.

**Comment by Ahmard** [comment] 2022-01-31 14:08
> This looks like a very tricky one. I got this reported by a user, on a project where I depend on endroid/qr-code.
> 
> I was not able to reproduce it with any combination of options. Later, when I requested more info to the user, he was no longer able to reproduce it either.
> 
> @Ahmard is it happening consistently for you?

No.
I can't really figure out why it was happening.

**Comment by endroid** [comment] 2022-01-31 17:24
@PhoenixBWS Thanks for your input. That test also turns green, see https://github.com/endroid/qr-code/actions/runs/1773941557 so it is still unclear why you have those errors on your side.

**Comment by endroid** [comment] 2022-02-01 20:30
Strange, but good to hear the issue disappeared. @PhoenixBWS Given that information, maybe it's worth to give it a try again on PHP 8. Make sure you update your Composer packages or even physically remove your vendor folder and composer cache just to be sure. Anyway, please let me know if you have any new information and I will try to help.

**Closed by endroid** 2022-02-01 20:30 UTC
Labels: bug

**Comment by ubaidismail** [comment] 2023-04-18 16:59
Hello, So I was using this library and still getting the same error so I moved to this libraray [SimpleSoftwareIO](https://github.com/SimpleSoftwareIO/simple-qrcode/issues?q=is%3Aissue+is%3Aopen+index+invalid)
But still, got the same error "Index invalid or out for range" Any one help? 
Thanks.

**Comment by endroid** [comment] 2023-04-18 17:11
Hi @ubaidismail in https://github.com/Bacon/BaconQrCode/issues/92 we found out it's a bug / instability in PHP, not in one of the libraries. I don't know if there is a solution yet for that specific case.

**Comment by ubaidismail** [comment] 2023-04-18 17:47
Do we have any other option to use QR code library?
Regards & Thanks,
Phone: +971 50 736 4124
Skype: https://join.skype.com/invite/XscCe8FMb7EJ
Web: Cloudtach.com | Portfolio <https://ubaidismail.github.io/portfolio/>
Ubaid Ismail | Full Stack Developer.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
18/04/23,
22:46:31
