### ISSUE TITLE
php8 - GD-Image is no longer a resource

### ISSUE THREAD

**Issue by adnanDeve** [endroid/qr-code#295] opened 2021-01-30 22:55 UTC
hi,
just installed xampp with php8.0.1 and tried out this library. but no image was rendered, instead "Unable to generate image: check your GD installation" was thrown. so i came up with this page: https://php.watch/versions/8.0/gdimage
it recommends to use:
if (is_resource($image) || $image instanceof \GdImage)
instead of:
if (is_resource($image))

so i changed for now just the PngWriter-class.

**Comment by endroid** [comment] 2021-01-31 08:15
Duplicate of https://github.com/endroid/qr-code/issues/287

**Closed by endroid** 2021-01-31 08:15 UTC
Labels: duplicate

**Comment by endroid** [comment] 2021-03-05 13:15
In the new 4.0.0 version which is PHP 8.0 compatible both resource and GdImage are supported.
